### ISSUE TITLE
Mandy's Team -  Review the "System" SAS jobs for remediaton

### ISSUE THREAD

**Issue by roundtr** [roundtr/SAS-SQL-Conversion#24]
- [x] SY1MLK01

- [x] SYSMKL3B

- [x] SY1MLK3P

- [x] SY1MLK42

- [x] SY1MLK4P

- [x] SY1MLK6B

- [x] SY1MLK6D

- [x] SY1MLK6O

- [x] SY1MLK6P

- [x] SY1MLK7S

- [x] SY1MLKB4

- [x] SY1MLKCP

- [x] SY1MLKFM

- [x] SY1MLKH3

- [x] SY1MLKL2

- [x] SY1MLKNF

- [x] SY1MLKP1

- [x] SY1MLKP2

- [x] SY1MLKP3

- [x] SY1MLKP7

- [x] SY1MLKPX

- [x] SY1MLKS1

- [x] SY1MLKS2

- [x] SY1MLKS3

- [x] SY1MLKS4

- [x] SY1MLKX1

- [x] SY1MLKX2

- [x] SY1MLKX3

- [x] SY1MLKX4

- [x] SY1MXGMK

- [x] SY1MXG01

**Comment by mustrij** [comment]
Although the documented job names may be unique, it is not an indicator that the same SAS code executes for a given job when executed.  For example SAS job X might be executing a report for SMF type 30 records on use 'A', and the next execution of SAS job X might be a SAS report for sytem information on CPU for PN1.  That is, it is not practical to see what jobs SY1MLK01, or SYSMKL3B, or .........., SY1MXG01 are executing in regard to SAS because they can each be doing completely typs of ad-hoc reports on a different execution the same day or on other days. 

The only practical approach is to "test" products such as Spectrum SMF writer using scenarios that are similar to SAS producing reports for SMF 30, 70, 74, 77.... and many others to see if similar reports can be produced.
